version: "3.5"
services:
  indexer:
    build: .
    networks:
      - indexer_network
    links:
      - clickhouse
    depends_on:
      - clickhouse
    environment:
      DB_URL: "clickhouse://clickhouse:9000/${DB_NAME}?sslmode=disable"
      FROM_BLOCK: ${FROM_BLOCK}
  clickhouse:
    image: "yandex/clickhouse-server"
    networks:
      - indexer_network
    volumes:
      - idx_db_data:/var/lib/clickhouse
    expose:
      - "9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

networks:
  indexer_network:

volumes:
  idx_db_data:
