version: "3.5"
services:
  indexer:
    build: .
    networks:
      - indexer_network
    links:
      - clickhouse
      - postgres
    depends_on:
      - clickhouse
      - postgres
    environment:
      DB_CH_URL: "clickhouse://clickhouse:9000/${DB_NAME}?sslmode=disable"
      DB_PG_URL: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
      FROM_BLOCK: ${FROM_BLOCK}
      LITESERVERS: ${LITESERVERS}
      DEBUG_LOGS: ${DEBUG_LOGS}
  query:
    build: .
    networks:
      - indexer_network
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - clickhouse
      - postgres
    depends_on:
      - clickhouse
      - postgres
    command: query
    environment:
      DB_CH_URL: "clickhouse://clickhouse:9000/${DB_NAME}?sslmode=disable"
      DB_PG_URL: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
      GIN_MODE: "release"
  clickhouse:
    image: "yandex/clickhouse-server"
    networks:
      - indexer_network
    volumes:
      - idx_ch_data:/var/lib/clickhouse
    ports:
      - "9000:9000"
    expose:
      - "9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  postgres:
    image: "postgres:15"
    command: ["postgres", "-c", "log_min_duration_statement=1000", "-c", "logging_collector=on"]
    networks:
      - indexer_network
    volumes:
      - idx_pg_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./log/postgresql:/var/lib/postgresql/data/log
    ports:
      - "5432:5432"
    expose:
      - "5432"
    shm_size: 64gb
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

networks:
  indexer_network:

volumes:
  idx_ch_data:
  idx_pg_data:
