version: "3.5"

x-anton-service: &anton-service
  image: "${IMAGE_NAME:-tonindexer/anton}:${IMAGE_TAG:-latest}"
  networks:
    - indexer_network
  environment: &anton-env
    DB_CH_URL: "clickhouse://${DB_USERNAME}:${DB_PASSWORD}@clickhouse:9000/${DB_NAME}?sslmode=disable"
    DB_PG_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"

services:
  indexer:
    <<: *anton-service
    depends_on:
      migrations:
        condition: service_completed_successfully
    command: idx
    environment:
      <<: *anton-env
      FROM_BLOCK: ${FROM_BLOCK}
      WORKERS: ${WORKERS}
      LITESERVERS: ${LITESERVERS}
      DEBUG_LOGS: ${DEBUG_LOGS}
      NUM_PARTITIONS: ${NUM_PARTITIONS}
    networks:
      - indexer_network
    logging:
      driver: "json-file"
      options:
        max-file: "5" # number of files or file count
        max-size: "10m" # file size
  rescan:
    <<: *anton-service
    depends_on:
      migrations:
        condition: service_completed_successfully
    command: rescan
    environment:
      <<: *anton-env
      RESCAN_WORKERS: ${RESCAN_WORKERS}
      RESCAN_SELECT_LIMIT: ${RESCAN_SELECT_LIMIT}
      LITESERVERS: ${LITESERVERS}
      DEBUG_LOGS: ${DEBUG_LOGS}
  web:
    <<: *anton-service
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: web
    environment:
      <<: *anton-env
      LITESERVERS: ${LITESERVERS}
      GIN_MODE: "release"
  migrations:
    <<: *anton-service
    command: ["migrate", "up", "--init"]
networks:
  indexer_network:
