version: "3.5"
services:
  indexer:
    image: "${IMAGE_NAME:-anton}:${IMAGE_TAG:-latest}"
    networks:
      - indexer_network
    links:
      - clickhouse
      - postgres
    depends_on:
      - clickhouse
      - postgres
    environment:
      DB_CH_URL: "clickhouse://clickhouse:9000/${DB_NAME}?sslmode=disable"
      DB_PG_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
      FROM_BLOCK: ${FROM_BLOCK}
      LITESERVERS: ${LITESERVERS}
      DEBUG_LOGS: ${DEBUG_LOGS}
  query:
    image: "${IMAGE_NAME:-anton}:${IMAGE_TAG:-latest}"
    networks:
      - indexer_network
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - clickhouse
      - postgres
    depends_on:
      - clickhouse
      - postgres
    command: query
    environment:
      DB_CH_URL: "clickhouse://clickhouse:9000/${DB_NAME}?sslmode=disable"
      DB_PG_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
      GIN_MODE: "release"
  clickhouse:
    image: "yandex/clickhouse-server:22"
    networks:
      - indexer_network
    volumes:
      - idx_ch_data:/var/lib/clickhouse
    expose:
      - "9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  postgres:
    image: "postgres:15"
    networks:
      - indexer_network
    volumes:
      - idx_pg_data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

networks:
  indexer_network:

volumes:
  idx_ch_data:
  idx_pg_data:
