version: "3.5"

x-anton-rewrites: &anton-rewrites
  build: .
  image: "${IMAGE_NAME:-anton}:${IMAGE_TAG:-latest}"

services:
  indexer:
    <<: *anton-rewrites
  web:
    <<: *anton-rewrites
  migrations:
    <<: *anton-rewrites
  clickhouse:
    ports:
      - "9000:9000"
      - "8123:8123"
  postgres:
    ports:
      - "5432:5432"
