version: "3.5"

x-anton-rewrites: &anton-rewrites
  build: .
  image: "${IMAGE_NAME:-anton}:${IMAGE_TAG:-latest}"

services:
  indexer:
    <<: *anton-rewrites
  rescan:
    <<: *anton-rewrites
  web:
    <<: *anton-rewrites
  migrations:
    <<: *anton-rewrites
