version: "3.5"
services:
  indexer:
    build: .
    networks:
      - indexer_network
    links:
      - clickhouse
      - postgres
    depends_on:
      - clickhouse
      - postgres
    environment:
      DB_CH_URL: "clickhouse://clickhouse:9000/${DB_NAME}?sslmode=disable"
      DB_PG_URL: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
      FROM_BLOCK: ${FROM_BLOCK}
      LITESERVERS: ${LITESERVERS}
  query:
    build: .
    networks:
      - indexer_network
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - clickhouse
      - postgres
    depends_on:
      - clickhouse
      - postgres
    command: query
    environment:
      DB_CH_URL: "clickhouse://clickhouse:9000/${DB_NAME}?sslmode=disable"
      DB_PG_URL: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
      GIN_MODE: "release"
  clickhouse:
    image: "yandex/clickhouse-server"
    networks:
      - indexer_network
    volumes:
      - idx_ch_data:/var/lib/clickhouse
    ports:
      - "9000:9000"
    expose:
      - "9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  postgres:
    image: "postgres:15"
    networks:
      - indexer_network
    volumes:
      - idx_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

networks:
  indexer_network:

volumes:
  idx_ch_data:
  idx_pg_data:
