name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: wisp-400514
  GCP_PROJECT_ID_NUM: 21632338263
  GCP_SERVICE_ACCOUNT: artifact-registry-writer@wisp-400514.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_POOL: github
  GCP_WORKLOAD_IDENTITY_POOL_PROVIDER: github-anyaxis-labs
  ARTIFACT_REGISTRY_LOCATION: asia-southeast1-docker.pkg.dev
  DOCKER_REPO_NAME: anyaxis-labs
  IMAGE_NAME: ton-indexer

jobs:
  build-push:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set envs
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}
          IMAGE_TAG=$SHORT_SHA
          DOCKER_IMAGE=$ARTIFACT_REGISTRY_LOCATION/$GCP_PROJECT_ID/$DOCKER_REPO_NAME/$IMAGE_NAME:$SHORT_SHA
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> "$GITHUB_ENV"

      - uses: google-github-actions/auth@v2
        with:
          project_id: "${{ env.GCP_PROJECT_ID }}"
          workload_identity_provider: "projects/${{ env.GCP_PROJECT_ID_NUM }}/locations/global/workloadIdentityPools/${{ env.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ env.GCP_WORKLOAD_IDENTITY_POOL_PROVIDER }}"
          service_account: "${{ env.GCP_SERVICE_ACCOUNT }}"

      - name: Docker login
        run: |
          gcloud auth print-access-token | docker login --password-stdin -u oauth2accesstoken https://$ARTIFACT_REGISTRY_LOCATION

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # name invalid: Missing image name. Pushes should be of the form docker push HOST-NAME/PROJECT-ID/REPOSITORY/IMAGE
      # Error: Process completed with exit code 1.
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "${{ env.DOCKER_IMAGE }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
